
import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from '../context/AuthContext';
import api from '../utils/api';

export async function generateMetadata(): Promise<Metadata> {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:3001/api'}/settings`, { cache: 'no-store' });
  const settings = await res.json();

  return {
    title: settings.metaTitle || "DEAL DIVERSify - Multivendor Store",
    description: "Generated by create next app",
    icons: {
      icon: settings.metaLogoUrl || "/favicon.ico",
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
      </head>
      <body className="flex flex-col min-h-screen">
        <AuthProvider>
            <main className="flex-grow">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
